### ISSUE TITLE
Long configuration description causes layout problem

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#1]
Meraki App 1.6

The long description on the dashboard config parameter causes a layout issue on the Asset screen:

![screen shot 2016-06-22 at 7 35 40 pm](https://cloud.githubusercontent.com/assets/1728937/16290273/c6649e10-38b0-11e6-81f6-b2b0c11304a3.png)

Normally the two fields would line up vertically.

It's possible to provide a default value for a field in the JSON. Suggest shortening the description to just "Dashboard URL" and supplying dashboard.meraki.com as the default value.

**Comment by ryanlrussell** [comment]
Also, can explain in a more verbose way in the App documentation section if desired.

**Comment by joelwking** [comment]
Applied to version 1.7
