### ISSUE TITLE
Long Action parameter description causes layout issue on Launch Action dialog

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#2]
Meraki App 1.6

Whenever possible, Action parameter descriptions should be limited to one line when laid out on the Launch Action dialog. Currently, the parameters for the "locate device" Action take 2 and 3 lines, causing the fields to not align vertically:

![screen shot 2016-06-22 at 7 41 13 pm](https://cloud.githubusercontent.com/assets/1728937/16290383/b9eab506-38b1-11e6-8e85-71caebc40a62.png)

Suggest something like "Partial MAC address or *" and "Timespan in seconds", and provide further documentation in the App doc.

**Comment by joelwking** [comment]
Applied to version 1.7
