### ISSUE TITLE
Would like logo with white or transparent background

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#3]
Meraki App 1.6

If available, a vendor logo with a transparent or white background is idea. The current one has an off-white background. Screenshot with the current logo, and some neighboring ones for comparison:

![screen shot 2016-06-22 at 7 48 03 pm](https://cloud.githubusercontent.com/assets/1728937/16290499/c04c3d56-38b2-11e6-8730-97d79768c075.png)

**Comment by joelwking** [comment]
Yes, I located a logo using white lettering on green. It is consistent with the OpenDNS and urlQuery logo.
