### ISSUE TITLE
unblock ip should be action type "correct"

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#5]
F5 App 2.0

The unblock ip action should be action type "correct" rather than "contain". Contain is for actions that restrict something (so your block ip action is correct as it's under contain). But the undo/unrestrict actions go under "correct". Right now, installing your App with the ones that come with Phantom makes it so that "unblock ip" now appears under both correct and contain.

Recommend that the JSON for unblock ip be changed to:

```
  {
    "action": "unblock ip",
    "description": "Deletes the rule which blocks an IP address",
    "type": "correct",
    "identifier": "unblock ip",
    "read_only": false,
    "parameters": {
...
```

Where "type" has been changed to "correct".

**Comment by joelwking** [comment]
Fixed in app_version  2.1
