### ISSUE TITLE
Set contains and primary for source field

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#6]
F5 App 2.0

(Apologies in advance if I'm misunderstanding the "source" field, I believe it must be the IP address. If that's not right please disregard and close.)

For the block ip action, I believe the "source" field is the IP address to be blocked, yes? If so, I recommend that it be tagged primary and contains "ip". So it would then look like this:

```
      "source": {
        "description": "packet source address",
        "contains": [ "ip" ],
        "primary": true,
        "data_type": "string",
        "required": true
      },
```

Note addition of the contains and primary lines.

**Comment by joelwking** [comment]
Fixed in app_version  2.1
