### ISSUE TITLE
Would like shorter action field descriptions

### ISSUE THREAD

**Issue by ryanlrussell** [joelwking/Phantom-Cyber#7]
F5 App 2.0

Ideally when possible, we would like action parameter descriptions to be limited to one line in the UI, so that fields are laid out in alignment. Currently, the block ip Launch Action dialog looks like this:

![screen shot 2016-06-23 at 2 00 12 pm](https://cloud.githubusercontent.com/assets/1728937/16320136/23457c72-394b-11e6-9fa6-8105721f7445.png)

And unblock ip:

![screen shot 2016-06-23 at 2 03 08 pm](https://cloud.githubusercontent.com/assets/1728937/16320161/456e6958-394b-11e6-896a-e83395e4928f.png)

(Unblock ip isn't as much of a problem since there's no other field next to "Partition" to have a misalignment, but ideally would still be a one-liner. If you change it for block ip, probably want to make the fields in unblock ip match.)

Some suggestions for wording or other changes:
Action: Might just want the description to be Action,or Rule action, and have it be a fixed list of options that turns into a drop-down. (Based on the current description, it sounds like it's a fixed list.)

Doing that would look like:

```
      "action": {
        "description": "Rule action ",
        "data_type": "string",
        "required": true,
        "value_list":["accept","drop", "reject"]
      }
```

Partition: Might suggest "Partition or path for the firewall policy"

Looks like the rest are already one line.

**Comment by joelwking** [comment]
Fixed in app_version  2.1
